import java.util.HashMap;

public class Lexico{

    public static String consertaFormatacao(String cadeia){
        cadeia=cadeia.replaceAll(" -> ","->");
        cadeia=cadeia.replaceAll(" ->","->");
        cadeia=cadeia.replaceAll("-> ","->");
        return cadeia;
    }

    public static HashMap<String,String> novoLexico(){
        HashMap<String,String> lexico=new HashMap<String,String>();
        String dadosDoLexico="Adjetivo->bela\n"
                +"Adjetivo->bom\n"
                +"Adjetivo->bonita\n"
                +"Adjetivo->cinco\n"
                +"Adjetivo->dois\n"
                +"Adjetivo->esgotado\n"
                +"Adjetivo->grande\n"
                +"Adjetivo->incrível\n"
                +"Adjetivo->insubstituível\n"
                +"Adjetivo->meus\n"
                +"Adjetivo->má\n"
                +"Adjetivo->verde\n"
                +"Adjetivo->único\n"
                +"Adjunto->como\n"
                +"Advérbio->muitas\n"
                +"Advérbio->não\n"
                +"Artigo->a\n"
                +"Artigo->as\n"
                +"Artigo->o\n"
                +"Artigo->os\n"
                +"Artigo->um\n"
                +"Artigo->uma\n"
                +"Artigo->umas\n"
                +"Artigo->uns\n"
                +"Preposição->ante\n"
                +"Preposição->ao\n"
                +"Preposição->aos\n"
                +"Preposição->após\n"
                +"Preposição->até\n"
                +"Preposição->com\n"
                +"Preposição->contra\n"
                +"Preposição->da\n"
                +"Preposição->dali\n"
                +"Preposição->daquela\n"
                +"Preposição->daquelas\n"
                +"Preposição->daquele\n"
                +"Preposição->daqueles\n"
                +"Preposição->daqui\n"
                +"Preposição->daquilo\n"
                +"Preposição->das\n"
                +"Preposição->daí\n"
                +"Preposição->de\n"
                +"Preposição->dela\n"
                +"Preposição->delas\n"
                +"Preposição->dele\n"
                +"Preposição->deles\n"
                +"Preposição->desde\n"
                +"Preposição->dessa\n"
                +"Preposição->dessas\n"
                +"Preposição->desse\n"
                +"Preposição->desses\n"
                +"Preposição->desta\n"
                +"Preposição->destas\n"
                +"Preposição->deste\n"
                +"Preposição->destes\n"
                +"Preposição->disso\n"
                +"Preposição->disto\n"
                +"Preposição->do\n"
                +"Preposição->dos\n"
                +"Preposição->doutra\n"
                +"Preposição->doutras\n"
                +"Preposição->doutro\n"
                +"Preposição->doutros\n"
                +"Preposição->dum\n"
                +"Preposição->duma\n"
                +"Preposição->dumas\n"
                +"Preposição->duns\n"
                +"Preposição->em\n"
                +"Preposição->entre\n"
                +"Preposição->na\n"
                +"Preposição->naquela\n"
                +"Preposição->naquelas\n"
                +"Preposição->naquele\n"
                +"Preposição->naqueles\n"
                +"Preposição->naquilo\n"
                +"Preposição->nas\n"
                +"Preposição->nela\n"
                +"Preposição->nelas\n"
                +"Preposição->nele\n"
                +"Preposição->neles\n"
                +"Preposição->nessa\n"
                +"Preposição->nessas\n"
                +"Preposição->nesse\n"
                +"Preposição->nesses\n"
                +"Preposição->nesta\n"
                +"Preposição->nestas\n"
                +"Preposição->neste\n"
                +"Preposição->nestes\n"
                +"Preposição->nisso\n"
                +"Preposição->nisto\n"
                +"Preposição->no\n"
                +"Preposição->nos\n"
                +"Preposição->num\n"
                +"Preposição->numa\n"
                +"Preposição->numas\n"
                +"Preposição->nuns\n"
                +"Preposição->para\n"
                +"Preposição->pela\n"
                +"Preposição->pelas\n"
                +"Preposição->pelo\n"
                +"Preposição->pelos\n"
                +"Preposição->per\n"
                +"Preposição->perante\n"
                +"Preposição->por\n"
                +"Preposição->pra\n"
                +"Preposição->pras\n"
                +"Preposição->pro\n"
                +"Preposição->pros\n"
                +"Preposição->sem\n"
                +"Preposição->sob\n"
                +"Preposição->sobre\n"
                +"Preposição->trás\n"
                +"Preposição->à\n"
                +"Preposição->àquela\n"
                +"Preposição->àquelas\n"
                +"Preposição->àquele\n"
                +"Preposição->àqueles\n"
                +"Preposição->àquilo\n"
                +"Preposição->às\n"
                +"Pronome demonstrativo->aquela\n"
                +"Pronome demonstrativo->aquelas\n"
                +"Pronome demonstrativo->aquele\n"
                +"Pronome demonstrativo->aqueles\n"
                +"Pronome demonstrativo->aquilo\n"
                +"Pronome demonstrativo->essa\n"
                +"Pronome demonstrativo->essas\n"
                +"Pronome demonstrativo->esse\n"
                +"Pronome demonstrativo->esses\n"
                +"Pronome demonstrativo->esta\n"
                +"Pronome demonstrativo->estas\n"
                +"Pronome demonstrativo->este\n"
                +"Pronome demonstrativo->estes\n"
                +"Pronome demonstrativo->isso\n"
                +"Pronome demonstrativo->isto\n"
                +"Pronome indefinido->algo\n"
                +"Pronome indefinido->algum\n"
                +"Pronome indefinido->alguma\n"
                +"Pronome indefinido->algumas\n"
                +"Pronome indefinido->alguns\n"
                +"Pronome indefinido->alguém\n"
                +"Pronome indefinido->muita\n"
                +"Pronome indefinido->muitas\n"
                +"Pronome indefinido->muito\n"
                +"Pronome indefinido->muitos\n"
                +"Pronome indefinido->nada\n"
                +"Pronome indefinido->nada\n"
                +"Pronome indefinido->nenhum\n"
                +"Pronome indefinido->nenhuma\n"
                +"Pronome indefinido->nenhumas\n"
                +"Pronome indefinido->nenhuns\n"
                +"Pronome indefinido->ninguém\n"
                +"Pronome indefinido->outra\n"
                +"Pronome indefinido->outras\n"
                +"Pronome indefinido->outrem\n"
                +"Pronome indefinido->outro\n"
                +"Pronome indefinido->outros\n"
                +"Pronome indefinido->pouca\n"
                +"Pronome indefinido->poucas\n"
                +"Pronome indefinido->pouco\n"
                +"Pronome indefinido->poucos\n"
                +"Pronome indefinido->quaisquer\n"
                +"Pronome indefinido->qualquer\n"
                +"Pronome indefinido->quanta\n"
                +"Pronome indefinido->quantas\n"
                +"Pronome indefinido->quanto\n"
                +"Pronome indefinido->quantos\n"
                +"Pronome indefinido->tanta\n"
                +"Pronome indefinido->tantas\n"
                +"Pronome indefinido->tanto\n"
                +"Pronome indefinido->tantos\n"
                +"Pronome indefinido->toda\n"
                +"Pronome indefinido->todas\n"
                +"Pronome indefinido->todo\n"
                +"Pronome indefinido->todos\n"
                +"Pronome indefinido->tudo\n"
                +"Pronome indefinido->vária\n"
                +"Pronome indefinido->várias\n"
                +"Pronome indefinido->vário\n"
                +"Pronome indefinido->vários\n"
                +"Pronome pessoal do caso reto->ela\n"
                +"Pronome pessoal do caso reto->elas\n"
                +"Pronome pessoal do caso reto->ele\n"
                +"Pronome pessoal do caso reto->eles\n"
                +"Pronome pessoal do caso reto->eu\n"
                +"Pronome pessoal do caso reto->nós\n"
                +"Pronome pessoal do caso reto->tu\n"
                +"Pronome pessoal do caso reto->vós\n"
                +"Pronome->a\n"
                +"Pronome->aquelas\n"
                +"Pronome->aqueles\n"
                +"Pronome->as\n"
                +"Pronome->dos\n"
                +"Pronome->esses\n"
                +"Pronome->estes\n"
                +"Pronome->o\n"
                +"Pronome->os\n"
                +"Pronome->uma\n"
                +"Substantivo->João\n"
                +"Substantivo->Maria\n"
                +"Substantivo->aluno\n"
                +"Substantivo->alunos\n"
                +"Substantivo->amigo\n"
                +"Substantivo->amigos\n"
                +"Substantivo->camisa\n"
                +"Substantivo->casa\n"
                +"Substantivo->chuva\n"
                +"Substantivo->crianças\n"
                +"Substantivo->esforço\n"
                +"Substantivo->festa\n"
                +"Substantivo->filho\n"
                +"Substantivo->galo-da-campina\n"
                +"Substantivo->homens\n"
                +"Substantivo->joão\n"
                +"Substantivo->livro\n"
                +"Substantivo->livros\n"
                +"Substantivo->livros\n"
                +"Substantivo->manhã\n"
                +"Substantivo->meninas\n"
                +"Substantivo->menino\n"
                +"Substantivo->meninos\n"
                +"Substantivo->pais\n"
                +"Substantivo->paz\n"
                +"Substantivo->português\n"
                +"Substantivo->professor\n"
                +"Substantivo->pássaros\n"
                +"Substantivo->redação\n"
                +"Substantivo->segundas-feiras\n"
                +"Substantivo->sobrinhos\n"
                +"Substantivo->sorte\n"
                +"Substantivo->sábados\n"
                +"Verbo de ligação->está\n"
                +"Verbo intransitivo->estudo\n"
                +"Verbo transitivo->escreveu\n"
                +"Verbo transitivo->prometia\n"
                +"Verbo->ama\n"
                +"Verbo->amam\n"
                +"Verbo->compreende\n"
                +"Verbo->desejam\n"
                +"Verbo->estuda\n"
                +"Verbo->foram\n"
                +"Verbo->lê\n"
                +"Verbo->lêem\n"
                +"Verbo->pega\n"
                +"Verbo->pegam\n"
                +"Verbo->saíram\n"
                +"Verbo->tem\n"
                +"Verbo->trabalha\n"
                +"Verbo->trabalho\n"
                +"Verbo->viram\n"
                +"Verbo->é";
        for(String linha:dadosDoLexico.split("\n")){
            linha=consertaFormatacao(linha); // pode ser que não seja necessário
            String argumentos[]=linha.split("->");
            lexico.put(argumentos[1],argumentos[0]);
        }
        return lexico;
    }
}
